### ISSUE TITLE
.bs-alert style fixes

### ISSUE THREAD

**Issue by tomlutzenberger** [bs-detector/bs-detector#119]
# z-index
Sometimes websites use fixed or absolute headers/navs and also z-index.
Our class has a z-index of 999, whereas e.g. Bootstraps navbars use a value between 1000 - 1100.
First discovered on: www.bento.de

Suggestion:
```css
.bs-alert {
  z-index: 9999;
}
```

Realised www.focus.de:

```css
.ressort-wrapper {
  z-index: 2147483647;
}
```

Going to be hard to make this work. That number is the maximum possible integer value.

# closing button position

If pages have a vertical scrollbar, the close button gets covered.
More margin is needed. Suggestion: 
```css
.bs-alert-close {
  margin-right: 2vw;
  font-weight: bold;
}
```
